"""initial migrations

Revision ID: d0b59d4e0043
Revises: 65134d882b02
Create Date: 2021-12-15 02:16:18.550373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b59d4e0043'
down_revision = '65134d882b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('projectid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('projectName', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('projectid')
    )
    op.add_column('file', sa.Column('projectid', sa.Integer(), nullable=True))
    op.drop_column('file', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('userid', sa.INTEGER(), nullable=True))
    op.drop_column('file', 'projectid')
    op.drop_table('project')
    # ### end Alembic commands ###
