"""Initial migration

Revision ID: f7b13d8b17ce
Revises: 
Create Date: 2022-03-21 05:04:23.543106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b13d8b17ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('fileid', sa.Integer(), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('fileid')
    )
    op.create_table('model',
    sa.Column('modelid', sa.Integer(), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=10000), nullable=True),
    sa.Column('classnames', sa.String(length=10000), nullable=True),
    sa.Column('createddate', sa.DateTime(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('confusion_matrix', sa.String(length=10000), nullable=True),
    sa.Column('class_report', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('modelid')
    )
    op.create_table('project',
    sa.Column('projectid', sa.String(length=400), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('projectName', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('projectid')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('model')
    op.drop_table('file')
    # ### end Alembic commands ###
