"""Initial migration

Revision ID: fdaf0cb70533
Revises: 
Create Date: 2022-02-05 20:48:24.615242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaf0cb70533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('userid', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
